name: Reusable Test

on:
  workflow_call:              # "mujhe doosra workflow bhi call kar sakta hai"
    inputs:
      python-version:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
      - run: pip install pytest
      - run: pytest